name: dlkinematics
on:
  push:
    branches:
      - "*/**"
  pull_request:
    branches:
      - "*/**"
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker container
        run: |
          docker build -t dlkinematics_tests .
      - name: Run tests
        run: |
          docker run -it -v $PWD:/work dlkinematics_tests python3 -m pytest
