name: dlkinematics
on:
  push:
    branches:
      - "*/**"
  pull_requests:
    branches:
      - "*/**"
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/action-build-test-container
